---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: zltch/nexus
    github.com/team-slug: group:github/admin
    backstage.io/kubernetes-id: minikube
  name: nexus
  namespace: nexus
  description: Nexus
  links:
    - url: https://github.com/zltch/nexus
      title: Github Repository
      icon: code
spec:
  type: website
  lifecycle: development
  owner: group:github/admin
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: zltch/nexus-catalog
    github.com/team-slug: group:github/admin
  name: nexus-catalog
  namespace: nexus
  description: Nexus Catalog
  links:
    - url: https://github.com/zltch/nexus-catalog
      title: Github Repository
      icon: code
spec:
  type: catalog
  lifecycle: development
  owner: group:github/admin
  dependencyOf:
    - component:nexus/nexus