# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-group
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  namespace: github
  description: Backstage Admin
spec:
  type: admin
  profile:
    displayName: Admin
  members: [user:default/zleetch]
  children: [group:github/infrastructure, group:github/site-reliability]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  namespace: github
  description: Infrastructure Team
spec:
  type: infra
  profile:
    displayName: Infrastructure
  members: [user:default/zleetch]
  children: [group:github/site-reliability]
  parent: [group:github/admin]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: site-reliability
  namespace: github
  description: Site Reliability Engineer
spec:
  type: infra
  profile:
    displayName: Site Reliability
  members: []
  children: []
  parent: [group:github/infrastructure]