# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-group
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  namespace: github
  description: Backstage Admin
spec:
  type: admin
  profile:
    displayName: Admin
  members: [user:zleetch]
  children: []