# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: zleetch
  namespace: github
spec:
  memberOf: [group:github/admin]