---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: zleetch
spec:
  memberOf: [group:github/admin, group:github/infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: testing
spec:
  memberOf: [group:github/admin]